<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \SoftCommerce\SeoSuite\ViewModel\HtmlHeadCanonical $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php if ($url = $viewModel->getCanonicalUrl()): ?>
    <link rel="canonical" href="<?= $url; ?>">
<?php endif; ?>
