<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/** @var \SoftCommerce\SeoSuite\Block\Html\Head\Hreflang $block */
?>
<?php foreach ($block->getLinkAttributes() as $attribute): ?>
    <?php if (isset($attribute['href'], $attribute['hreflang'])): ?>
        <link rel="alternate" hreflang="<?= $attribute['hreflang']; ?>" href="<?= $attribute['href']; ?>">
    <?php endif; ?>
<?php endforeach; ?>
<?php if ($xDefaultUrl = $block->getLinkXDefaultUrlAttribute()): ?>
    <link rel="alternate" href="<?= $xDefaultUrl; ?>" hreflang="x-default">
<?php endif; ?>
