<?php
/**
 * Copyright © Soft Commerce Ltd. All rights reserved.
 * See LICENSE.txt for license details.
 */
?>
<?php
/**
 * @var \Magento\Framework\View\Element\Template $block
 * @var \SoftCommerce\SeoSuite\ViewModel\HtmlHeadHreflang $viewModel
 */
$viewModel = $block->getViewModel();
?>
<?php foreach ($viewModel->getLinkAttributes() as $attribute): ?>
    <?php if (isset($attribute['href'], $attribute['hreflang'])): ?>
        <link rel="alternate" hreflang="<?= $attribute['hreflang']; ?>" href="<?= $attribute['href']; ?>">
    <?php endif; ?>
<?php endforeach; ?>
<?php if ($xDefaultUrl = $viewModel->getLinkXDefaultUrlAttribute()): ?>
    <link rel="alternate" hreflang="x-default" href="<?= $xDefaultUrl; ?>">
<?php endif; ?>
