<?php
/**
 * Adds hreflang tags for language and regional URLs used by search engines.
 *
 * @see https://support.google.com/webmasters/answer/189077
 * @see https://jira.pluswerk.ag/browse/ROL-140
 */
?>
<?php
/** @var \SoftCommerce\SeoSuite\Block\Html\Head\Hreflang $block */
?>
<?php foreach ($block->getLinkAttributes() as $attribute): ?>
    <?php if (isset($attribute['href'], $attribute['hreflang'])): ?>
        <link rel="alternate" href="<?= $attribute['href']; ?>" hreflang="<?= $attribute['hreflang']; ?>">
    <?php endif; ?>
<?php endforeach; ?>
<?php if ($xDefaultUrl = $block->getLinkXDefaultUrlAttribute()): ?>
    <link rel="alternate" href="<?= $xDefaultUrl; ?>" hreflang="x-default">
<?php endif; ?>
